### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by aabarrigas** [ElmarJ/volumio-plugins#1]
How can I install this plugin?

**Comment by ElmarJ** [comment]
Dear aabarigas,

Unfortunately, downloading and "side-loading" plugins as a .zip-file is no longer allowed in volumio. I have placed a "pull request" to include the plugin in the volumio plugin-system. Once that request is approved, you can easily add the plugin from within Volumio. For now, we'll simply have to wait.

Best, Elmar
